/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetofarmacia;

import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author gustavo
 */
public class CadastroMedicamento extends javax.swing.JFrame {
private Conexao mdbc;
    private java.sql.Statement stmt;
    /**
     * Creates new form CadastroMedicamento
     */
    public CadastroMedicamento() throws SQLException {
        mdbc = new Conexao();
        mdbc.init();
        Connection conn = mdbc.getMyConnection();
        stmt= conn.createStatement();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("ProjetoFarmacia?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        fornecedor_1Query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT f FROM Fornecedor_1 f");
        fornecedor_1List = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : fornecedor_1Query.getResultList();
        cliente_1Query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Cliente_1 c");
        cliente_1List = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : cliente_1Query.getResultList();
        produtoQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Produto p");
        produtoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : produtoQuery.getResultList();
        fornecedor_1Query1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT f FROM Fornecedor_1 f");
        fornecedor_1List1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : fornecedor_1Query1.getResultList();
        produtoQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Produto p");
        produtoList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : produtoQuery1.getResultList();
        fornecedor_1Query2 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT f FROM Fornecedor_1 f");
        fornecedor_1List2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : fornecedor_1Query2.getResultList();
        produtoQuery2 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Produto p");
        produtoList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : produtoQuery2.getResultList();
        produtoQuery3 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Produto p");
        produtoList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : produtoQuery3.getResultList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTDOSAGEM = new javax.swing.JTextField();
        jTCADASTROREMEDIO = new javax.swing.JTextField();
        jTPRECO = new javax.swing.JTextField();
        jTMARCA = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTConsulta = new javax.swing.JTable();
        jBCADASTRAR = new javax.swing.JButton();
        jBREMOVER = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLCADASTRO = new javax.swing.JLabel();
        jTFVALIDADE = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome do Remédio:");

        jLabel2.setText("Dosagem :");

        jLabel4.setText("Preço :");

        jLabel5.setText("Validade :");

        jLabel6.setText("Marca :");

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, produtoList, jTConsulta);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codRemedio}"));
        columnBinding.setColumnName("Cod Remedio");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${quantidade}"));
        columnBinding.setColumnName("Quantidade");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${marca}"));
        columnBinding.setColumnName("Marca");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${validade}"));
        columnBinding.setColumnName("Validade");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane1.setViewportView(jTConsulta);

        jBCADASTRAR.setText("Cadastrar");
        jBCADASTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCADASTRARActionPerformed(evt);
            }
        });

        jBREMOVER.setText("Remover");
        jBREMOVER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBREMOVERActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Cadastrar Medicamentos");

        jLCADASTRO.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        jTFVALIDADE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(2, 2, 2)
                                .addComponent(jTCADASTROREMEDIO, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTDOSAGEM))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTPRECO))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFVALIDADE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTMARCA)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                            .addComponent(jLCADASTRO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBCADASTRAR)
                        .addGap(18, 18, 18)
                        .addComponent(jBREMOVER)
                        .addGap(309, 309, 309))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jLCADASTRO, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTCADASTROREMEDIO, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTDOSAGEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTFVALIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTPRECO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTMARCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCADASTRAR)
                    .addComponent(jBREMOVER))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCADASTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCADASTRARActionPerformed
    String nome = jTCADASTROREMEDIO.getText();
        String dosagem = jTDOSAGEM.getText();
        String validade = jTFVALIDADE.getText();
        String preco = jTPRECO.getText();
        String marca = jTMARCA.getText();
        
        if( "".equals(nome) | "".equals(dosagem) |"".equals(validade) 
                | "".equals(preco) | "".equals(marca))
        {
            jLCADASTRO.setText("Há campos vazios!");
            jLCADASTRO.setForeground(Color.RED);
        } 
        else {
            
            String insertStr = "";
           
            try
            {
                insertStr = "insert into Produto (Nome, Quantidade, validade, marca) values('"
                +nome+"','"
                +dosagem+"','"
                +validade+"','"
                +marca+"')";

                System.out.println(insertStr);
                int done = stmt.executeUpdate(insertStr);
                getContentPane().removeAll();
                initComponents();
                jLCADASTRO.setText("Um registro inserido!");
                jLCADASTRO.setForeground(Color.BLUE);
            }

            catch(Exception e)
            {
               jLCADASTRO.setText("Erro ao inserir registro!");
                jLCADASTRO.setForeground(Color.RED);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jBCADASTRARActionPerformed

    private void jBREMOVERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBREMOVERActionPerformed
      Integer Cod_Remedio=-1;
        try{
            Cod_Remedio = (Integer)jTConsulta.getValueAt(jTConsulta.getSelectedRow(), 0);
        }catch(Exception e){}    
        System.out.println(Cod_Remedio);
        
        String insertStr = "";
        if(Cod_Remedio !=-1){
            try{
                insertStr = "delete from Produto where Cod_Remedio = '"+Cod_Remedio+"'";
                System.out.println(insertStr);
                stmt.executeUpdate(insertStr);
                getContentPane().removeAll();
                initComponents();
                jLCADASTRO.setForeground(Color.BLUE);
                jLCADASTRO.setText("Um registro foi apagado!");
            }
            catch(Exception e){
                jLCADASTRO.setForeground(Color.RED);
                jLCADASTRO.setText("Erro ao apagar um registro!");
            }
        }else{
            jLCADASTRO.setForeground(Color.RED);
            jLCADASTRO.setText("Selecione um registro na Tabela!");
        }  // TODO add your handling code here:
    }//GEN-LAST:event_jBREMOVERActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CadastroMedicamento().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(CadastroMedicamento.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<projetofarmacia.Cliente_1> cliente_1List;
    private javax.persistence.Query cliente_1Query;
    private javax.persistence.EntityManager entityManager;
    private java.util.List<projetofarmacia.Fornecedor_1> fornecedor_1List;
    private java.util.List<projetofarmacia.Fornecedor_1> fornecedor_1List1;
    private java.util.List<projetofarmacia.Fornecedor_1> fornecedor_1List2;
    private javax.persistence.Query fornecedor_1Query;
    private javax.persistence.Query fornecedor_1Query1;
    private javax.persistence.Query fornecedor_1Query2;
    private javax.swing.JButton jBCADASTRAR;
    private javax.swing.JButton jBREMOVER;
    private javax.swing.JLabel jLCADASTRO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCADASTROREMEDIO;
    private javax.swing.JTable jTConsulta;
    private javax.swing.JTextField jTDOSAGEM;
    private javax.swing.JFormattedTextField jTFVALIDADE;
    private javax.swing.JTextField jTMARCA;
    private javax.swing.JTextField jTPRECO;
    private java.util.List<projetofarmacia.Produto> produtoList;
    private java.util.List<projetofarmacia.Produto> produtoList1;
    private java.util.List<projetofarmacia.Produto> produtoList2;
    private java.util.List<projetofarmacia.Produto> produtoList3;
    private javax.persistence.Query produtoQuery;
    private javax.persistence.Query produtoQuery1;
    private javax.persistence.Query produtoQuery2;
    private javax.persistence.Query produtoQuery3;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
